output "argocd_namespace" {
  description = "Namespace where Argo CD is installed."
  value       = var.argocd_namespace
}

output "argocd_admin_password" {
  description = "Argo CD admin password (generated by Terraform; also retrievable via `terraform output -raw argocd_admin_password`)."
  value       = random_password.argocd_admin.result
  sensitive   = true
}
